name: dy_flutter
description: Douyu App of flutter.
version: 1.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^3.1.0
  path_provider: ^1.1.2
  flutter_screenutil: ^0.5.3
  flutter_swiper: ^1.1.6
  flutter_bloc: ^6.1.1
  rxdart: ^0.24.1
  equatable: ^0.3.0
  dio: ^3.0.0
  dio_http_cache: ^0.2.11
  video_player: ^1.0.1
  image_picker: ^0.6.7
  flutter_webview_plugin: ^0.3.11
  pull_to_refresh: ^1.5.5
  web_socket_channel: ^1.0.15
  shared_preferences: ^0.5.12
  cached_network_image: ^2.1.0
  photo_view: ^0.9.0
  # barcode_scan: ^3.0.1
  flutter_local_notifications: ^3.0.1
  lottie: ^0.7.0

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/pic-default.jpg
    - images/back.webp
    - images/default-avatar.webp
    - images/shayuniang.png
    - images/search.webp
    - images/cfk.webp
    - images/hot.png
    - images/member.png
    - images/play.png
    - images/gift.png
    - images/gift-banner.png
    - images/gift-x.png
    - images/gift-1.png
    - images/float-icon.webp
    - images/init_logo.webp
    - images/init_icon.png
    - images/show-area.webp
    - images/broadcast.webp
    - images/fun_home_pull_down.png
    - images/cjf.webp
    - images/dg.webp
    - images/dg0.webp
    - images/cqe.webp
    - images/num/0.webp
    - images/num/1.webp
    - images/num/2.webp
    - images/num/3.webp
    - images/num/4.webp
    - images/num/5.webp
    - images/num/6.webp
    - images/num/7.webp
    - images/num/8.webp
    - images/num/9.webp
    - images/cate/tab-0.webp
    - images/cate/tab-1.webp
    - images/cate/tab-2.webp
    - images/cate/tab-3.webp
    - images/cate/tab-4.webp
    - images/cate/tab-5.webp
    - images/cate/tab-6.webp
    - images/cate/tab-7.webp
    - images/cate/tab-8.webp
    - images/cate/tab-9.webp
    - images/cate/tab-10.webp

    - images/login/syn.webp
    - images/login/qq.webp
    - images/login/wx.webp
    - images/login/weibo.webp
    - images/login/close.webp
    - images/login/safe.webp
    - images/login/member.webp
    - images/login/lock.webp

    - images/head/dylogo.png
    - images/head/camera.webp
    - images/head/chat.webp
    - images/head/game.webp
    - images/head/history.webp

    - images/lv/3.png
    - images/lv/30.png
    - images/lv/50.png
    - images/lv/80.png

    - images/nav/nav-11.jpg
    - images/nav/nav-21.jpg
    - images/nav/nav-31.jpg
    - images/nav/nav-41.jpg
    - images/nav/nav-51.jpg
    - images/nav/nav-12.jpg
    - images/nav/nav-22.jpg
    - images/nav/nav-32.jpg
    - images/nav/nav-42.jpg
    - images/nav/nav-52.jpg

    - images/bar/hot-chat.jpg
    - images/bar/day-title.png
    - images/bar/hot-title.png
    - images/bar/pull-icon.webp
    - images/bar/usefulSelect.webp
    - images/bar/girl.webp
    - images/bar/boy.webp
    - images/bar/tab-0.png
    - images/bar/tab-1.png
    - images/bar/tab-2.png
    - images/bar/chat-add.jpg
    - images/bar/chat-share.jpg
    - images/bar/chat-star.jpg
    - images/bar/chat-star-act.webp
